vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /image/products
    #        upload_destination: '%kernel.project_dir%/public/image/products'

    mappings:
        property_image:
            uri_prefix: /image/properties
            upload_destination: '%kernel.project_dir%/public/image/properties'
            namer: Vich\UploaderBundle\Naming\UniqidNamer